const list = [
  {
    id: 1,
    title: "Men's jersey 1",
    author: "Warriors Stephen Curry 2022 NBA Finals Diamond Edition Black Jersey",
    price: 999 ,
    img: "https://www.nbajerseystore.us/image/golden-state-warriors/golden-state-warriors-stephen-curry-black-2022-nba-finals-jersey-0a.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Men's Jersey 2",
    author: "Stephen Curry Warriors Black 2019 NBA Finals Statement Jersey",
    price: 988,
    img: "https://www.nbajerseystore.us/images/golden-state-warriors/warriors-stephen-curry-2019-nba-finals-black-statement-jersey.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Men's jersey 3",
    author: "Warriors Stephen Curry 2022 NBA Finals Association White Jersey",
    price: 143,
    img: "https://www.nbajerseystore.us/image/golden-state-warriors/golden-state-warriors-klay-thompson-white-2022-nba-finals-jersey.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Men's jersey 4",
    author: "Warriors Stephen Curry 2022 NBA Finals Statement Yellow Jersey",
    price: 577,
    img: "https://www.nbajerseystore.us/image/golden-state-warriors/golden-state-warriors-stephen-curry-yellow-2022-nba-finals-jersey-0a.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Men's jersey 5",
    author: "Warriors Kevon Looney 2022 NBA Finals Icon Blue Jersey",
    price: 1449,
    img: "https://www.nbajerseystore.us/image/golden-state-warriors/golden-state-warriors-draymond-green-blue-2022-nba-finals-jersey.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Men's jersey 6",
    author: "Warriors Draymond Green Fadeaway Swingman Hardwood Classics Jersey",
    price: 135,
    img: "https://www.nbajerseystore.us/images/golden-state-warriors/draymond-green-hardwood-classics-men-gold/royal-jersey.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Men's jersey 7 ",
    author: "Celtics Derrick White Fadeaway 2022 NBA Finals Jersey",
    price: 693,
    img: "https://www.nbajerseystore.us/images/boston-celtics/jayson-tatum-2022-nba-finals-men-green/black-jersey.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Men's jersey 8",
    author: "Marcus Smart Celtics 2022 NBA Finals Fast Break Replica Green Icon Jersey",
    price: 289,
    img: "https://www.nbajerseystore.us/image/boston-celtics/boston-celtics-marcus-smart-green-2022-nba-finals-jersey-0a.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Men's jersey 9 ",
    author: "Celtics Jayson Tatum 2022 NBA Finals Statement Black Jersey",
    price: 80,
    img: "https://www.nbajerseystore.us/image/boston-celtics/boston-celtics-jayson-tatum-black-2022-nba-finals-jersey.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Men's jersey 10",
    author: "Men Warriors Kevon Looney 2021-22 NBA Champions Jersey",
    price: 86,
    img: "https://www.nbajerseystore.us/images/golden-state-warriors/kevon-looney-2021-22-nba-champions-royal-hardwood-classics-men-jersey.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Men's jersey 11",
    author: "Stephen Curry Warriors 2022 Royal Independence Day Jersey",
    price: 1200,
    img: "https://www.nbajerseystore.us/images/golden-state-warriors/warriors-stephen-curry-jersey-royal-4th-of-july-independence-day-men.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Men's jersey 12",
    author: "Seattle SuperSonics Shawn Kemp Green Throwback Jersey",
    price: 157,
    img: "https://www.nbajerseystore.us/images/seattle-supersonics/supersonics-shawn-kemp-1994-95-hardwood-classics-green-jersey.jpg",
    amount: 1,
  },
];

export default list;
